### PR TITLE
Make sybil test init files

### PR DESCRIPTION
**Pull request by Marenz**

### CODE REVIEW

**Comment by Marenz** [comment]
```
❰marenz❙~/frequenz/frequenz-quantities-python(gitinitsybil)❱✔≻ pytest
===================================================================================== test session starts =====================================================================================
platform linux -- Python 3.11.9, pytest-8.2.2, pluggy-1.5.0
rootdir: /home/marenz/frequenz/frequenz-quantities-python
configfile: pyproject.toml
testpaths: tests, src
plugins: asyncio-0.23.7, mock-3.14.0, hypothesis-6.104.2
asyncio: mode=Mode.AUTO
collected 206 items

tests/test_quantities.py .............................................................................................................................................................. [ 76%]
..............................................                                                                                                                                          [ 99%]
src/frequenz/quantities/__init__.py .                                                                                                                                                   [ 99%]
src/frequenz/quantities/_quantity.py .                                                                                                                                                  [100%]

==================================================================================== 206 passed in 12.73s =====================================================================================
❰
```

**Review by llucax — COMMENTED** [review]
I also tried adding an error to the example in `__init__.py` and was properly detected. I would say we close this and make the changes directly in repo-config.

**Comment by Marenz** [comment]
I am still wondering if a certain complexity of imports could cause problems...

**Comment by llucax** [comment]
Maybe try it in the SDK and channels repos too? Those are probably the repos with more files and more examples.

**Comment by llucax** [comment]
I think this was confirmed to work correctly now. Should we just go and fix repo-config instead and make a patch release with the fix so it is propagated to all repos automatically instead of adding this hack?

**Comment by llucax** [comment]
Haha, I wrote almost the same comment 3 weeks ago. Let's go for it in `repo-config`. If it doesn't work for some complex repo, we can always rollback, but keep adding this hack to more and more repos will make the rolling back much more complicated than handling it indirectly via `repo-config`.

**Comment by Marenz** [comment]
https://github.com/frequenz-floss/frequenz-repo-config-python/pull/321

**Pull request closed without merging**
